name: Replace static images with Workers AI

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Test workflow
        run: echo "workflow is valid"
